#!/usr/bin/env python3
import sys

input1 = bytes.fromhex("1c0111001f010100061a024b53535009181c")
input2 = bytes.fromhex("686974207468652062756c6c277320657965")
expected_output = "746865206b696420646f6e277420706c6179"


def xor(a, b):
    r = int.from_bytes(a, sys.byteorder) ^ int.from_bytes(b, sys.byteorder)
    return r.to_bytes(len(a), sys.byteorder)


output = xor(input1, input2).hex()


print("Expected Output: {}".format(expected_output))
print("My Output:       {}".format(output))

if output == expected_output:
    print("Pass!")
else:
    print("Fail!")
