#!/usr/bin/env python3
import base64

input = "49276d206b696c6c696e6720796f757220627261696e206c696b65206120706f69736f6e6f7573206d757368726f6f6d"
expected_output = "SSdtIGtpbGxpbmcgeW91ciBicmFpbiBsaWtlIGEgcG9pc29ub3VzIG11c2hyb29t"

i = bytes.fromhex(input)
output = base64.b64encode(i).decode()

print("Expected Output: {}".format(expected_output))
print("My Output      : {}".format(output))

if output == expected_output:
    print("Pass!")
else:
    print("Fail!")
