#!/usr/bin/env python3
import base64
from Crypto.Cipher import AES

key = "YELLOW SUBMARINE".encode()
input = None
with open("input.txt") as f:
    input = base64.b64decode(f.read())

c = AES.new(key, AES.MODE_ECB)
r = c.decrypt(input)
p = r[:-r[-1]]  # Strip the padding
print('=== "Decrypted" Text ===')
print(p.decode())
